# docs: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/go"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/go"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/python"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows/"
    schedule:
      interval: "weekly"
