{
 "title": "COVID 19 Dashboard",
 "description": "Dashboard tracking the spread of COVID-19 in the United States in realtime.",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "US Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "US Cases Total",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(covid_19_cases_total{state!=\"\",date!=\"3/22/2020\"})"
    }
   ]
  },
  {
   "title": "US Cases Today (24h window)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(covid_19_todayCases_total{state!=\"\",date!=\"3/22/2020\"})"
    }
   ]
  },
  {
   "title": "Cases by State",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(covid_19_cases_total{state!=\"\"}) by (state)",
     "legendFormat": "{{ state }}"
    },
    {
     "expr": "sum(covid_19_today_cases_total{state!=\"\"}) by (state)",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "US Cases Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "sum(covid_19_cases_total) by (country)"
    }
   ]
  },
  {
   "title": "US Cases Today",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "targets": [
    { "expr": "sum(covid_19_todayCases_total)" }
   ]
  },
  {
   "title": "US Cases Total by State",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(covid_19_cases_total{state!=\"\",date!=\"3/22/2020\"}) by (state))",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "US Cases Daily by State",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(covid_19_todayCases_total{state!=\"\",date!=\"3/22/2020\"}) by (state)  ",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Cases by State, as % of Country",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 13 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "covid_19_cases_total{state!=\"\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "US Total Deaths",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 13 },
   "targets": [
    { "expr": "sum(covid_19_deaths_total)" }
   ]
  },
  {
   "title": "Florida Cases Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(covid_19_cases_total{state=\"Florida\"})"
    }
   ]
  },
  {
   "title": "Tennessee Cases Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 25 },
   "targets": [
    {
     "expr": "sum(covid_19_cases_total{state=\"Tennessee\"})"
    }
   ]
  }
 ]
}