app = "covid-exporter"
primary_region = "mia"

[build]
image = "rushsimonson/covid-exporter:go-0.0.4"

[http_service]
internal_port = 8000
force_https = false
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/metrics"
