name: Test and build on PR

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ^1.21.6
        id: go
      - run: go version

      - name: run tests
        run: |
          cd go && \
          make build && \
          make test
